name: lydband
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  http: ^1.2.1
  crypto: ^3.0.3
  rsa_encrypt: ^2.0.0
  encrypt: ^5.0.3
  charset: ^2.0.1
  fast_rsa: ^3.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/img/

